name: db-tests

on:
  pull_request:
    paths:
      - "tm2/pkg/db/**.go"
      - "go.sum"
      - ".github/workflows/db-tests.yml"
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        goversion:
          - "1.20.x"
          - "1.21.x"
    steps:
      - uses: actions/checkout@v4

      # golang
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}

      # leveldb
      - name: install database dependencies
        if: ${{ matrix.tags=='cleveldb' }}
        run: sudo apt-get install -y librocksdb8.3 libleveldb-dev

      - name: Set environment variables for debug mode
        if: env.ACTIONS_STEP_DEBUG == 'true'
        run: |
          export LOG_PATH_DIR=${{ runner.temp }}/logs
          mkdir -p $LOG_PATH_DIR

          echo "LOG_LEVEL=debug" >> $GITHUB_ENV
          echo "LOG_PATH_DIR=$LOG_PATH_DIR" >> $GITHUB_ENV

      # test ./pkgs/db
      - name: test ./tm2/pkg/db
        run: go test -v ./tm2/pkg/db/...
